source ~/dotfiles/vim/plugins.vim

set number
set expandtab
set shiftwidth=2
set softtabstop=2
set mouse=a
colorscheme angr

let g:rspec_command = 'call Send_to_Tmux("rspec {spec}\n")'
let g:ctrlp_show_hidden = 1

map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
map <Leader>q :vsp .<CR>
map <Leader>0 ^i

nmap <leader>w :w<CR>
nmap <leader>wq :wq<CR>
nmap <leader>- :sp<CR><C-p>
nmap <leader>\ :vsp<CR><C-p>
nmap <leader>o o<Esc>k
nmap <leader>O O<Esc>j

imap jk <Esc>:w<CR>
imap kj <Esc>:w<CR>
imap <leader>o <C-o>o
imap <leader>O <C-o>O

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

autocmd!
au CursorHoldI <buffer> stopinsert
au FocusLost,BufLeave * wa
syntax on

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
highlight TrailingSpaces ctermbg=red ctermfg=white guibg=#592929

match TrailingSpaces /\s$/

function ShowOver80Chars()
  match OverLength /\%81v.\+/
endfunction

function HideOver80Chars()
  match OverLength //
endfunction
