---
- hosts: localhost
  tasks:
  - name: Installing wget
    homebrew:
      name: wget
      state: present
  - name: Installing git
    homebrew:
      name: git
      state: present
  - name: Installing tmux
    homebrew:
      name: tmux
      state: present
  - name: Installing hack-for-tmux-and-macOS
    homebrew:
      name: reattach-to-user-namespace
      state: present
  - name: Installing vim 8
    homebrew:
      name: vim@8.0
      state: present
  - name: Installing Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
  - name: Installing rbenv
    homebrew:
      name: rbenv
      state: present
  - name: Installing ruby-build
    homebrew:
      name: ruby-build
      state: present
  - name: Installing oh my zsh
    shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  - name: Changing default shell for Xavier
    shell: chsh -s /bin/zsh Xavier
  - name: Creating colors folder inside .vim
    file:
      path: ~/.vim/colors
      state: directory
  - name: Creating ftplugin folder inside .vim
    file:
      path: ~/.vim/ftplugin
      state: directory
  - name: Linking dotfiles
    file:
      src: '~/dotfiles/{{ item.src }}'
      dest: '~/{{ item.dest }}'
      state: link
      force: yes
    with_items:
        - { src: 'vim/vimrc', dest: '.vimrc' }
        - { src: 'vim/angr.vim', dest: '.vim/colors/angr.vim' }
        - { src: 'vim/ftplugin', dest: '.vim/ftplugin' }
        - { src: 'zsh/zshrc', dest: '.zshrc' }
        - { src: 'tmux/tmux.conf', dest: '.tmux.conf' }
        - { src: 'global_gitignore', dest: '.gitignore' }
        - { src: 'zsh/avit_modified.zsh-theme', dest: '.oh-my-zsh/themes/avit_modified.zsh-theme' }
  - name: Installing vim plugins
    command: vim +PluginInstall +qall
