export PATH="/Users/xavier.simo/.local/bin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/bin:/usr/bin:$PATH"
export PATH="/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/X11/bin:/usr/texbin:$HOME/go/bin:$HOME/.node/bin:$PATH"
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
export PATH="/opt/homebrew/opt/mysql-client@8.0/bin:$PATH"
export PATH="/opt/homebrew/opt/python@3.13/libexec/bin:$PATH"


# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export GOPATH=$HOME/go

export PATH="/Users/xavier.simo/.oly/bin:$PATH"
export TERM="screen-256color"

export APPLE_SSH_ADD_BEHAVIOR=macos

export EVENT_NOKQUEUE=1
export EDITOR='nvim'
export GIT_EDITOR='nvim'

setopt noautocd

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="avit_modified"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true”

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(docker git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
# export EDITOR='subl -w'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

alias ls='ls -lahG'
alias be='bundle exec'
alias rubocurrent='bundle exec rubocop $(git status | egrep modified.*rb | sed s/modified://)'
alias fco='git checkout $(git branch | fzf)'
alias gitcurrentbranch='git branch --abbrev | grep "*" | sed -E "s/\* //"'

unsetopt nomatch
eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Load zsh syntax highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# bun completions
[ -s "/Users/xavier.simo/.bun/_bun" ] && source "/Users/xavier.simo/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export PATH="/Users/xavier.simo/.local/state/fnm_multishells/178_1728401142043/bin":$PATH
export FNM_ARCH="arm64"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_MULTISHELL_PATH="/Users/xavier.simo/.local/state/fnm_multishells/178_1728401142043"
export FNM_DIR="/Users/xavier.simo/Library/Application Support/fnm"
export FNM_RESOLVE_ENGINES="false"
export FNM_COREPACK_ENABLED="false"
export FNM_LOGLEVEL="info"
export FNM_VERSION_FILE_STRATEGY="local"

export PATH="/Users/xavier.simo/.oly/bin:$PATH"
